services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j_import:/var/lib/neo4j/import
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=ClinicalQI_2026!
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ports:
      - "9200:9200"
      - "9600:9600"
